config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls'), name='main'),
    path('promos/', include('promo.urls'), name='promo'),
    path('users/', include('users.urls'), name='users'),
    path('doctors/', include('doctors.urls'), name='doctors'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path

from main.apps import MainConfig
from main.views import *

app_name = MainConfig.name

urlpatterns = [
    path('', IndexView.as_view(), name='index'),

    path('diagnostics/', DiagnosticCategoryListView.as_view(), name='diagnostics'),
    path('tests/', TestCategoryListView.as_view(), name='tests'),

    path('results/', ResultListView.as_view(), name='results'),
    path('results/create/', ResultCreateView.as_view(), name='result_create'),
    path('results/view/<int:pk>', ResultDetailView.as_view(), name='result_view'),
    path('results/update/<int:pk>', ResultUpdateView.as_view(), name='result_update'),
    path('results/delete/<int:pk>', ResultDeleteView.as_view(), name='result_delete'),

    path('appointment/', make_appointment, name='make_appointment'),
]

users/models.py
from django.utils import timezone

from django.contrib.auth.models import AbstractUser
from django.db import models


class User(AbstractUser):
    username = None  # удаляем поле username, так как авторизовать будем по полю email
    email = models.EmailField(unique=True, verbose_name='Email')

    first_name = models.CharField(max_length=50, verbose_name='Имя')
    last_name = models.CharField(max_length=50, verbose_name='Фамилия')

    birthday = models.DateField(verbose_name='Дата рождения', null=True)
    phone = models.CharField(max_length=35, verbose_name='Телефон', null=True)
    address = models.CharField(max_length=150, verbose_name='Адрес', null=True)
    photo = models.ImageField(upload_to='users/', verbose_name='Фото', null=True)
    comment = models.TextField(verbose_name='Комментарий', null=True)
    created_date = models.DateTimeField(default=timezone.now)
    modified_date = models.DateTimeField(auto_now=True, verbose_name='Modified date')
    is_active = models.BooleanField(default=False, verbose_name='Active')
    verification_token = models.CharField(max_length=50, null=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    def role(self, group_name):
        return self.groups.filter(name=group_name).exists()

    class Meta:
        verbose_name = 'Пользователь'
        verbose_name_plural = 'Пользователи'
        ordering = ('last_name',)
        permissions = [('activate_delete_users', 'Can activate/delete users'),]

    def __str__(self):
        return self.email

main/forms.py
from django import forms

from main.models import MedicalResult
from users.forms import StyleFormMixin
from users.models import User


class MedicalResultForm(StyleFormMixin, forms.ModelForm):

    class Meta:
        model = MedicalResult
        exclude = ('doctor',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        #  Передаем в форму список пользователей из get_user_queryset
        self.fields['user'].queryset = self.get_user_queryset()
        # Выводим этот список в виде 'Имя Фамилия' не трогая метод str() модели User
        self.fields['user'].label_from_instance = lambda obj: f"{obj.first_name} {obj.last_name}"

    def get_user_queryset(self):
        # Выбираем только тех пользователей, которые не входят ни в какую
        # группу (doctors, managers), то есть обычных пользователей/пациентов
        return User.objects.filter(groups__isnull=True)


class MedicalResultFileForm(StyleFormMixin, forms.Form):
    file = forms.FileField(label='Загрузить файл', required=False)
    file_description = forms.CharField(label='Описание файла', max_length=50, required=False)

main/views.py
import random
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.shortcuts import render
from django.urls import reverse, reverse_lazy
from django.views import generic
from django.views.generic import ListView, DetailView, FormView, UpdateView, DeleteView
from django.contrib.sites.shortcuts import get_current_site
from django.conf import settings

from doctors.models import Doctor
from main.forms import MedicalResultForm, MedicalResultFileForm
from main.models import DiagnosticCategory, TestCategory, MedicalResult, MedicalResultFile
from promo.models import Promo
from users.models import User
from users.tasks import send_notification_email


class IndexView(generic.View):

    @staticmethod
    def get(request):
        three_promo = []

        count_tests = MedicalResult.objects.all().count()
        count_doctors = Doctor.objects.all().count()
        # Считаем обычных пользователей (не входящих в группы doctors, managers, staff...)
        count_users = User.objects.filter(groups__isnull=True).count()

        # Выбираем три случайные акции (без повторов)
        all_active_promo = Promo.objects.filter(is_active=True)
        num_of_active_promo = all_active_promo.count()
        # if num_of_active_promo <= 3:
        #     three_promo = all_active_promo
        # else:
        #     while len(three_promo) < 3:
        #         i = random.randint(0, num_of_active_promo - 1)
        #         if all_active_promo[i] not in three_promo:
        #             three_promo.append(all_active_promo[i])


        # random.sample() оптимизирована для выбора случайных элементов из последовательности
        # без повторений и работает быстрее, чем ручное создание цикла с проверкой на уникальность
        three_promo = random.sample(list(all_active_promo), min(num_of_active_promo, 3))
        context = {
            'count_tests': count_tests,
            'count_doctors': count_doctors,
            'count_users': count_users,
            'object_list': three_promo,
        }
        return render(request, 'main/index.html', context)


class DiagnosticCategoryListView(ListView):
    model = DiagnosticCategory


class TestCategoryListView(ListView):
    model = TestCategory


class ResultListView(PermissionRequiredMixin, ListView):
    model = MedicalResult
    permission_required = 'main.modify_medical_results'

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.filter(doctor=self.request.user.pk)
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        medical_results = self.get_queryset()
        medical_result_files = {}
        for result in medical_results:
            try:
                medical_result_file = result.medicalresultfile
                if medical_result_file:
                    medical_result_files[result.id] = medical_result_file.file.url
            except MedicalResultFile.DoesNotExist:
                pass
        context['medical_result_files'] = medical_result_files
        return context


class ResultCreateView(PermissionRequiredMixin, FormView):
    model = MedicalResult
    form_class = MedicalResultForm
    file_form_class = MedicalResultFileForm
    permission_required = 'main.modify_medical_results'
    template_name = 'main/medicalresult_form.html'

    def form_valid(self, form):
        self.object = form.save(commit=False)  # Сначала сохраняем форму, но не в базу данных
        # Получаем объект врача, соответствующего текущему пользователю
        doctor = Doctor.objects.get(user=self.request.user)
        self.object.doctor = doctor  # Присваиваем врача записи MedicalResult
        self.object.save()  # Теперь сохраняем запись MedicalResult

        file_form = self.file_form_class(self.request.POST, self.request.FILES)
        if file_form.is_valid():
            file_description = file_form.cleaned_data['file_description']
            if 'file' in self.request.FILES:
                file_instance = MedicalResultFile(medical_result=self.object,
                                                  file=self.request.FILES['file'],
                                                  file_description=file_description)
                file_instance.save()
            send_notification_email.delay(
                self.object.user.email,
                'Новый результат обследования/анализа',
                f'Здравствуйте!\nВ вашем личном кабинете появился новый результат обследования/анализа\n'
                f'Для ознакомления пройдите по ссылке\n'
                f'http://{get_current_site(self.request)}/users/view/{self.object.user.pk}')
            return super().form_valid(form)
        else:
            return self.form_invalid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['file_form'] = self.file_form_class()
        return context

    def get_success_url(self):
        return reverse('main:result_view', args=[self.object.pk])

    def perform_create(self, serializer):
        instance = serializer.save()
        send_notification_email.delay(
            instance.user.email,
            'Новый результат обследования/анализа',
            f'Здравствуйте!\nВ вашем личном кабинете появился новый результат обследования/анализа\n'
            f'Для ознакомления пройдите по ссылке\n'
            f'http://{get_current_site(self.request)}/users/{self.object.pk}')


class ResultDetailView(PermissionRequiredMixin, DetailView):
    model = MedicalResult
    permission_required = 'main.modify_medical_results'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        medical_result = self.get_object()
        if hasattr(medical_result, 'medicalresultfile'):
            context['medical_result_file'] = medical_result.medicalresultfile.file.url
            context['medical_result_file_description'] = medical_result.medicalresultfile.file_description
        else:
            context['medical_result_file'] = None
        return context


class ResultUpdateView(PermissionRequiredMixin, UpdateView):
    model = MedicalResult
    form_class = MedicalResultForm
    file_form_class = MedicalResultFileForm
    permission_required = 'main.modify_medical_results'
    success_url = reverse_lazy('main:results')

    def get_queryset(self):
        return super().get_queryset().filter(doctor=self.request.user.pk)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        medical_result = self.object

        context['file_form'] = self.file_form_class()
        try:
            medical_result_file = medical_result.medicalresultfile
            context['medical_result_file'] = medical_result.medicalresultfile.file.url
            context['medical_result_file_description'] = medical_result_file.file_description
            initial_data = {
                'file_description': medical_result_file.file_description,
                'file': medical_result_file.file,
            }
            file_form = self.file_form_class(initial=initial_data)

        except MedicalResultFile.DoesNotExist:
            context['medical_result_file'] = None
            file_form = self.file_form_class()
        context['file_form'] = file_form
        return context

    def form_valid(self, form):
        self.object = form.save()

        file_form = MedicalResultFileForm(self.request.POST, self.request.FILES)
        if file_form.is_valid():
            file_description = file_form.cleaned_data['file_description']
            try:
                medical_result_file = self.object.medicalresultfile
                # Обновляем данные существующего файла
                medical_result_file.file_description = file_description
                if 'file' in self.request.FILES:
                    medical_result_file.file = self.request.FILES['file']
                elif file_form.cleaned_data['file'] is False:
                    medical_result_file.delete()
                else:
                    medical_result_file.save()
            except MedicalResultFile.DoesNotExist:
                # Создаем новый файл, если он не существует
                if 'file' in self.request.FILES:
                    file_instance = MedicalResultFile(
                        medical_result=self.object,
                        file=self.request.FILES['file'],
                        file_description=file_description
                    )
                    file_instance.save()
            send_notification_email.delay(
                self.object.user.email,
                'Обновление результатов обследования/анализа',
                f'Здравствуйте!\nВ вашем личном кабинете обновились результаты обследований/анализов\n'
                f'Для ознакомления пройдите по ссылке\n'
                f'http://{get_current_site(self.request)}/users/view/{self.object.user.pk}')
        return super().form_valid(form)


class ResultDeleteView(PermissionRequiredMixin, DeleteView):
    model = MedicalResult
    permission_required = 'main.modify_medical_results'
    success_url = reverse_lazy('main:results')

    def get_queryset(self):
        # Фильтруем запрос так, чтобы удаляемый результат принадлежал текущему пользователю
        return super().get_queryset().filter(doctor=self.request.user.pk)


def make_appointment(request):
    if request.user.pk:
        context = {
            'name': f'{request.user.first_name} {request.user.last_name}',
            'from': request.user.email,
            'phone': request.user.phone,
        }
    else:
        context = {}

    if request.method == 'POST':
        send_notification_email.delay(
            settings.MED_CENTER_EMAIL,
            f'Сообщение от пользователя {request.POST.get("name")}',
            f'{request.POST.get("message")}\n\n'

main/templates/main/appointment.html
{% extends 'main/base.html' %}

{% block content %}

<main class="container">
    <div class="my-3 p-3 bg-body rounded shadow-sm">
        <div class="container px-4 py-0">

            <div class="row mt-3">

                <div class="col-6">
                    <div class="card">
                        <div class="card-body">
                            <h3 class="card-header p-6 pb-md-4 mx-auto text-center">Наши контакты</h3>
                            <div class="row mt-3">
                                <div class="col-3">Адрес</div>
                                <div class="col-9">129090, город Москва, Большая<br>Сухаревская площадь, дом 3</div>
                                <div class="col-3">Телефоны</div>
                                <div class="col-9">+7 (800) 280-15-61 (звонок бесплатный)</div>
                                <div class="col-3"></div>
                                <div class="col-9">+7 (495) 280-15-61</div>
                                <div class="col-3">E-mail</div>
                                <div class="col-9">info@medcenter.com</div>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="col-6">
                    <div class="card">
                        <div class="card-body">
                            <h3 class="card-header p-6 pb-md-4 mx-auto text-center">Напишите нам</h3>
                            <div class="row mt-3">
                                <form method="post">
                                    {% csrf_token %}
                                    <div class="mb-3">
                                        <input name="name" type="text" class="form-control"
                                               id="exampleInputName" value="{{ name }}"
                                               aria-describedby="nameHelp" placeholder="Имя">
                                    </div>
                                    <div class="mb-3">
                                        <input name="email" type="email" class="form-control"
                                               id="exampleInputEmail" value="{{ from }}"
                                               aria-describedby="emailHelp" placeholder="Email">
                                    </div>
                                    <div class="mb-3">
                                        <input name="phone" type="phone" class="form-control"
                                               id="exampleInputPhone" value="{{ phone }}"
                                               aria-describedby="phoneHelp" placeholder="Телефон">
                                    </div>
                                    <div class="mb-3">
                                    <textarea name="message" class="form-control" id="exampleFormControlTextarea1"
                                              placeholder="Сообщение" rows="3"></textarea>
                                    </div>

                                    <div class="btn-group btn-group-sm form-control">
                                        <button type="submit" class="btn btn-secondary">Отправить</button>
                                        <a class="btn btn-outline-secondary" onclick="history.back();">Отмена</a>
                                    </div>

                                </form>
                            </div>
                        </div>
                    </div>

                </div>
            </div>

        </div>
    </div>
</main>
{% endblock %}

main/templates/main/base.html
{% load static %}
{% load users_tags %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="generator" content="Hugo 0.84.0">

    <title>Medical Center</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/accordion.css' %}" rel="stylesheet">

    <!-- Favicons -->
    <!--<link rel="apple-touch-icon" href="/docs/5.0/assets/img/favicons/apple-touch-icon.png" sizes="180x180">-->
    <!--<link rel="icon" href="/docs/5.0/assets/img/favicons/favicon-32x32.png" sizes="32x32" type="image/png">-->
    <!--<link rel="icon" href="/docs/5.0/assets/img/favicons/favicon-16x16.png" sizes="16x16" type="image/png">-->
    <!--<link rel="manifest" href="/docs/5.0/assets/img/favicons/manifest.json">-->
    <!--<link rel="mask-icon" href="/docs/5.0/assets/img/favicons/safari-pinned-tab.svg" color="#7952b3">-->
    <!--<link rel="icon" href="/docs/5.0/assets/img/favicons/favicon.ico">-->
    <meta name="theme-color" content="#7952b3">


    <style>
        .bd-placeholder-img {
          font-size: 1.125rem;
          text-anchor: middle;
          -webkit-user-select: none;
          -moz-user-select: none;
          user-select: none;
        }

        @media (min-width: 768px) {
          .bd-placeholder-img-lg {
            font-size: 3.5rem;
          }
        }

        /* Стиль для изменения вида курсора в таблицах */
        tr.link {
          cursor: pointer;
        }
    </style>

    <link href="{% static 'css/carousel.css' %}" rel="stylesheet">
</head>
<body>

<header>
    <nav class="navbar navbar-expand-md fixed-top bg-primary-subtle">
        <div class="container-fluid ">

            <a class="navbar-brand" href="/">
                <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor"
                     class="bi bi-heart-pulse" viewBox="0 0 16 16">
                    <path d="m8 2.748-.717-.737C5.6.281 2.514.878 1.4 3.053.918 3.995.78 5.323 1.508 7H.43c-2.128-5.697 4.165-8.83 7.394-5.857q.09.083.176.171a3 3 0 0 1 .176-.17c3.23-2.974 9.522.159 7.394 5.856h-1.078c.728-1.677.59-3.005.108-3.947C13.486.878 10.4.28 8.717 2.01zM2.212 10h1.315C4.593 11.183 6.05 12.458 8 13.795c1.949-1.337 3.407-2.612 4.473-3.795h1.315c-1.265 1.566-3.14 3.25-5.788 5-2.648-1.75-4.523-3.434-5.788-5"/>
                    <path d="M10.464 3.314a.5.5 0 0 0-.945.049L7.921 8.956 6.464 5.314a.5.5 0 0 0-.88-.091L3.732 8H.5a.5.5 0 0 0 0 1H4a.5.5 0 0 0 .416-.223l1.473-2.209 1.647 4.118a.5.5 0 0 0 .945-.049l1.598-5.593 1.457 3.642A.5.5 0 0 0 12 9h3.5a.5.5 0 0 0 0-1h-3.162z"/>
                </svg>
                <strong>Medical Center</strong>
            </a>

            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse"
                    aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarCollapse">
                <ul class="navbar-nav me-auto mb-2 mb-md-0">
                    <li class="nav-item">
                        <a class="nav-link" aria-current="page" href="{% url 'promo:promos' %}">Акции</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" aria-current="page" href="{% url 'main:diagnostics' %}">Диагностика</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'main:tests' %}">Анализы</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'doctors:doctors' %}">Доктора</a>
                    </li>

                    {% if request.user|has_group:"managers" %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:user_list' %}">Пациенты</a>
                    </li>
                    {% endif %}
                    {% if request.user|has_group:"doctors" %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'main:results' %}">Результаты анализов</a>
                    </li>
                    {% endif %}
                </ul>

                <div class="col-md-4 text-end">
                    {% if user.is_authenticated %}
                        <a href="{% url 'users:user_view' request.user.pk %}" type="button" class="btn btn-sm btn-outline-secondary me-2">{{ request.user }}</a>
                        <a href="{% url 'users:logout' %}" type="button" class="btn btn-sm btn-secondary">Выход</a>
                    {% else %}
                        <a href="{% url 'users:login' %}" type="button"
                           class="btn btn-sm btn-outline-secondary me-2">Вход</a>
                        <a href="{% url 'users:signup' %}" type="button" class="btn btn-sm btn-secondary">Регистрация</a>
                    {% endif %}
                </div>


            </div>
        </div>
    </nav>

</header>

    {% block content %}

    {% endblock %}

<footer class="container">
    <p class="float-end"><a href="#">Наверх</a></p>
    <p>&copy; 2024 Medical Center, Inc.</p>
</footer>

<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>


</body>
</html>

main/templates/main/diagnostic_form.html
{% extends 'main/base.html' %}
{% block content %}

<main class="container">
    <div class="my-3 p-3 bg-body rounded shadow-sm">
        <div class="container px-4 py-0">

            <form method="post" class="row" enctype="multipart/form-data">
                <div class="col-8">
                    <div class="card">
                        <div class="card-header">
                            {% if object %}
                            Edit message
                            {% else %}
                            Add message
                            {% endif %}
                        </div>
                        <div class="card-body">
                            {% csrf_token %}
                            {{ form.as_p }}
                        </div>
                        <div class="card-footer">
                            <div class="d-flex justify-content-between align-items-center">
                                <div class="btn-group">
                                    <button type="submit" class="btn btn-secondary">
                                        {% if object %}
                                        Save
                                        {% else %}
                                        Add
                                        {% endif %}
                                    </button>
                                    <a class="btn btn-outline-secondary" href="{% url 'main:diagnostics' %}">Cancel</a>
                                </div>
                            </div>
                        </div>
                    </div>
            </form>


        </div>
    </div>
</main>

{% endblock %}

main/templates/main/diagnostic_list.html
{% extends 'main/base.html' %}
{% block content %}

<main class="container">
    <div class="my-3 p-3 bg-body rounded shadow-sm">
        <div class="container px-4 py-0">


            <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
                <h3>Диагностика</h3>

                <div class="btn-toolbar mb-2 mb-md-0">
                    <a type="button" class="btn btn-sm btn-secondary" href="{% url 'main:diagnostic_create' %}">Добавить</a>
                </div>


            </div>
        </div>
    </div>
</main>

{% endblock %}

main/templates/main/diagnosticcategory_form.html
{% extends 'main/base.html' %}
{% block content %}

<main class="container">
    <div class="my-3 p-3 bg-body rounded shadow-sm">
        <div class="container px-4 py-0">

            <form method="post" class="row" enctype="multipart/form-data">
                <div class="col-8">
                    <div class="card">
                        <div class="card-header">
                            {% if object %}
                            Редактировать категорию
                            {% else %}
                            Добавить категорию
                            {% endif %}
                        </div>
                        <div class="card-body">
                            {% csrf_token %}
                            {{ form.as_p }}
                        </div>
                        <div class="card-footer">
                            <div class="d-flex justify-content-between align-items-center">
                                <div class="btn-group">
                                    <button type="submit" class="btn btn-secondary">
                                        {% if object %}
                                        Сохранить
                                        {% else %}
                                        Добавить
                                        {% endif %}
                                    </button>
                                    <a class="btn btn-outline-secondary" href="{% url 'main:diagnostics' %}">Отмена</a>
                                </div>
                            </div>
                        </div>
                    </div>

            </form>

        </div>
    </div>
</main>

{% endblock %}

main/templates/main/diagnosticcategory_list.html
{% extends 'main/base.html' %}
{% load users_tags %}
{% block content %}

<img src="/static/images/diagnostic.jpg" class="img-fluid" alt="Tests">

<main class="container">
    <div class="my-3 p-3 bg-body rounded shadow-sm">
        <div class="container px-4 py-0">

            <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
                <h3>Диагностика</h3>
            </div>

            <div class="accordion accordion-flush" id="accordionFlush">
                {% for object in object_list %}

                <div class="accordion-item">
                    <h2 class="accordion-header">
                        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse"
                                data-bs-target="#flush-{{ object.id }}" aria-expanded="false"
                                aria-controls="flush-{{ object.id }}">
                            <h5><strong>{{ object.name|truncatechars:100 }}</strong></h5>
                        </button>

                    </h2>

                    <div id="flush-{{ object.id }}" class="accordion-collapse collapse"
                         data-bs-parent="#accordionFlush">
                        <div class="accordion-body">

                            <ol class="list-group list-group-flush">

                                {% for diagnostic in object.diagnostics.all %}
                                <li class="list-group-item d-flex justify-content-between align-items-center">
                                    <div class="ms-2 me-auto">
                                        <div class="fw-bold">{{ diagnostic.name }} (Код {{ diagnostic.article }}) - {{ diagnostic.price }} руб.</div>
                                        {% if diagnostic.description %}
                                        {{ diagnostic.description }}
                                        {% endif %}
                                    </div>
                                    {% if not request.user|has_group:"doctors" %}
                                    <a type="button" class="btn btn-sm btn-outline-secondary"
                                       href="{% url 'main:make_appointment' %}">Записаться</a>
                                    {% endif %}
                                </li>
                                {% endfor %}
                            </ol>

                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>

        </div>
    </div>
</main>

{% endblock %}

main/templates/main/medicalresult_confirm_delete.html
{% extends 'main/base.html' %}
{% block content %}

<main class="container">
    <div class="my-3 p-3 bg-body rounded shadow-sm">
        <div class="container px-4 py-0">

            <form method="post" class="row">
                <div class="col-6">
                    <div class="card">
                        <div class="card-header">
                            Удаление результатов обследований
                        </div>
                        <div class="card-body">
                            {% csrf_token %}
                            <p>Вы действительно хотите удалить результаты обследований<br>{{ object.user.first_name }} {{ object.user.last_name }}?</p>
                            <button type="submit" class="btn btn-danger">Удалить</button>
                            <a class="btn btn-outline-warning" onclick="history.back();">Отмена</a>
                        </div>
                    </div>
                </div>
            </form>

        </div>
    </div>
</main>
{% endblock %}